# Generated by Django 2.0.3 on 2018-04-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180423_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='articles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
