# Generated by Django 2.0.3 on 2018-04-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_followrelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrelation',
            old_name='follwer',
            new_name='follower',
        ),
    ]
