# Generated by Django 2.0.3 on 2018-04-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='censure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='page_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='praise',
            field=models.IntegerField(default=0),
        ),
    ]
