# Generated by Django 2.0.3 on 2018-03-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180326_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='modifide_time',
            new_name='modified_time',
        ),
    ]
